cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "getantibody/antibody"
tap "github/gh"
tap "versent/taps"

brew "antibody"
brew "aws-iam-authenticator"
brew "awscli"
brew "docker-credential-helper-ecr"
brew "diff-so-fancy"
brew "ffmpeg"
brew "gh"
brew "git"
brew "go"
brew "gpg"
brew "gnupg"
brew "grc"
brew "htop"
brew "jq"
brew "mas"
brew "mkcert"
brew "node"
brew "shellcheck"
brew "telnet"
brew "terraform"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "versent/taps/saml2aws"
brew "wget"
brew "zsh"
brew "z"
brew "php"
brew "php@7.2"
brew "php@7.3"
brew "php@7.4"
brew "svn"
brew "lastpass-cli"
brew "tmux"
brew "navi"

# gnu stuff
brew "coreutils"
brew "findutils"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "gnu-indent"
brew "gnu-getopt"

cask "font-hack"
cask "font-jetbrains-mono"
cask "google-backup-and-sync"
cask "google-chrome"
cask "firefox-developer-edition"
cask "phpstorm"
cask "alacritty"
cask "slack"
cask "spotify"
cask "transmission"
cask "viscosity"
cask "vlc"
cask "zoom"
cask "plex-media-server"
cask "microsoft-teams"
cask "whatsapp"
cask "obs"
cask "kap"
cask "microsoft-outlook"
cask "android-file-transfer"
cask "jetbrains-toolbox"
cask "rectangle"

# MacApp Store Apps
mas "Bear", id: 1091189122
